// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: internal/testservice/stream.proto

package testservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// count is the number of messages to send before the handler does anything
	// else.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// fail_code is the RPC code to fail with once the messages have been sent,
	// which is what makes the handler answer with an error after the response
	// status has been written.
	FailCode string `protobuf:"bytes,2,opt,name=fail_code,json=failCode,proto3" json:"fail_code,omitempty"`
	// block keeps the stream open until the handler's context is done, which is
	// the shape of a subscription.
	Block bool `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
	// token_expiry makes the handler derive its context with
	// rpc.ContextWithTokenExpiry, so that the stream ends when the caller's
	// token expires.
	TokenExpiry   bool `protobuf:"varint,4,opt,name=token_expiry,json=tokenExpiry,proto3" json:"token_expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_internal_testservice_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_internal_testservice_stream_proto_rawDescGZIP(), []int{0}
}

func (x *EmitRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EmitRequest) GetFailCode() string {
	if x != nil {
		return x.FailCode
	}
	return ""
}

func (x *EmitRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

func (x *EmitRequest) GetTokenExpiry() bool {
	if x != nil {
		return x.TokenExpiry
	}
	return false
}

type EmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// number is the position of the message in the stream, counted from one.
	Number        int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_internal_testservice_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_internal_testservice_stream_proto_rawDescGZIP(), []int{1}
}

func (x *EmitResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type CollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_internal_testservice_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_internal_testservice_stream_proto_rawDescGZIP(), []int{2}
}

func (x *CollectRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CollectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      int64                  `protobuf:"varint,1,opt,name=messages,proto3" json:"messages,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectResponse) Reset() {
	*x = CollectResponse{}
	mi := &file_internal_testservice_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResponse) ProtoMessage() {}

func (x *CollectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResponse.ProtoReflect.Descriptor instead.
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return file_internal_testservice_stream_proto_rawDescGZIP(), []int{3}
}

func (x *CollectResponse) GetMessages() int64 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *CollectResponse) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type ExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_internal_testservice_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_testservice_stream_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_internal_testservice_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_testservice_stream_proto_rawDescGZIP(), []int{5}
}

func (x *ExchangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_testservice_stream_proto protoreflect.FileDescriptor

const file_internal_testservice_stream_proto_rawDesc = "" +
	"\n" +
	"!internal/testservice/stream.proto\x12\x1aelephantine.testservice.v1\"y\n" +
	"\vEmitRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1b\n" +
	"\tfail_code\x18\x02 \x01(\tR\bfailCode\x12\x14\n" +
	"\x05block\x18\x03 \x01(\bR\x05block\x12!\n" +
	"\ftoken_expiry\x18\x04 \x01(\bR\vtokenExpiry\"&\n" +
	"\fEmitResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\"*\n" +
	"\x0eCollectRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"C\n" +
	"\x0fCollectResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x01(\x03R\bmessages\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\"+\n" +
	"\x0fExchangeRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x10ExchangeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xbd\x02\n" +
	"\rStreamService\x12[\n" +
	"\x04Emit\x12'.elephantine.testservice.v1.EmitRequest\x1a(.elephantine.testservice.v1.EmitResponse0\x01\x12d\n" +
	"\aCollect\x12*.elephantine.testservice.v1.CollectRequest\x1a+.elephantine.testservice.v1.CollectResponse(\x01\x12i\n" +
	"\bExchange\x12+.elephantine.testservice.v1.ExchangeRequest\x1a,.elephantine.testservice.v1.ExchangeResponse(\x010\x01B2Z0github.com/ttab/elephantine/internal/testserviceb\x06proto3"

var (
	file_internal_testservice_stream_proto_rawDescOnce sync.Once
	file_internal_testservice_stream_proto_rawDescData []byte
)

func file_internal_testservice_stream_proto_rawDescGZIP() []byte {
	file_internal_testservice_stream_proto_rawDescOnce.Do(func() {
		file_internal_testservice_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testservice_stream_proto_rawDesc), len(file_internal_testservice_stream_proto_rawDesc)))
	})
	return file_internal_testservice_stream_proto_rawDescData
}

var file_internal_testservice_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_testservice_stream_proto_goTypes = []any{
	(*EmitRequest)(nil),      // 0: elephantine.testservice.v1.EmitRequest
	(*EmitResponse)(nil),     // 1: elephantine.testservice.v1.EmitResponse
	(*CollectRequest)(nil),   // 2: elephantine.testservice.v1.CollectRequest
	(*CollectResponse)(nil),  // 3: elephantine.testservice.v1.CollectResponse
	(*ExchangeRequest)(nil),  // 4: elephantine.testservice.v1.ExchangeRequest
	(*ExchangeResponse)(nil), // 5: elephantine.testservice.v1.ExchangeResponse
}
var file_internal_testservice_stream_proto_depIdxs = []int32{
	0, // 0: elephantine.testservice.v1.StreamService.Emit:input_type -> elephantine.testservice.v1.EmitRequest
	2, // 1: elephantine.testservice.v1.StreamService.Collect:input_type -> elephantine.testservice.v1.CollectRequest
	4, // 2: elephantine.testservice.v1.StreamService.Exchange:input_type -> elephantine.testservice.v1.ExchangeRequest
	1, // 3: elephantine.testservice.v1.StreamService.Emit:output_type -> elephantine.testservice.v1.EmitResponse
	3, // 4: elephantine.testservice.v1.StreamService.Collect:output_type -> elephantine.testservice.v1.CollectResponse
	5, // 5: elephantine.testservice.v1.StreamService.Exchange:output_type -> elephantine.testservice.v1.ExchangeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_testservice_stream_proto_init() }
func file_internal_testservice_stream_proto_init() {
	if File_internal_testservice_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testservice_stream_proto_rawDesc), len(file_internal_testservice_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_testservice_stream_proto_goTypes,
		DependencyIndexes: file_internal_testservice_stream_proto_depIdxs,
		MessageInfos:      file_internal_testservice_stream_proto_msgTypes,
	}.Build()
	File_internal_testservice_stream_proto = out.File
	file_internal_testservice_stream_proto_goTypes = nil
	file_internal_testservice_stream_proto_depIdxs = nil
}
