// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: internal/testservice/testservice.proto

package testservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_internal_testservice_testservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_testservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_internal_testservice_testservice_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Subject string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// log_metadata is what the service could see of the request log metadata,
	// which is what the parity tests compare between the two stacks.
	LogMetadata   map[string]string `protobuf:"bytes,3,rep,name=log_metadata,json=logMetadata,proto3" json:"log_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_internal_testservice_testservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_testservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_internal_testservice_testservice_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EchoResponse) GetLogMetadata() map[string]string {
	if x != nil {
		return x.LogMetadata
	}
	return nil
}

type FailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_internal_testservice_testservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_testservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_internal_testservice_testservice_proto_rawDescGZIP(), []int{2}
}

func (x *FailRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type FailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailResponse) Reset() {
	*x = FailResponse{}
	mi := &file_internal_testservice_testservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailResponse) ProtoMessage() {}

func (x *FailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testservice_testservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailResponse.ProtoReflect.Descriptor instead.
func (*FailResponse) Descriptor() ([]byte, []int) {
	return file_internal_testservice_testservice_proto_rawDescGZIP(), []int{3}
}

var File_internal_testservice_testservice_proto protoreflect.FileDescriptor

const file_internal_testservice_testservice_proto_rawDesc = "" +
	"\n" +
	"&internal/testservice/testservice.proto\x12\x1aelephantine.testservice.v1\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xe0\x01\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\\\n" +
	"\flog_metadata\x18\x03 \x03(\v29.elephantine.testservice.v1.EchoResponse.LogMetadataEntryR\vlogMetadata\x1a>\n" +
	"\x10LogMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\vFailRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x0e\n" +
	"\fFailResponse2\xc3\x01\n" +
	"\vTestService\x12Y\n" +
	"\x04Echo\x12'.elephantine.testservice.v1.EchoRequest\x1a(.elephantine.testservice.v1.EchoResponse\x12Y\n" +
	"\x04Fail\x12'.elephantine.testservice.v1.FailRequest\x1a(.elephantine.testservice.v1.FailResponseB2Z0github.com/ttab/elephantine/internal/testserviceb\x06proto3"

var (
	file_internal_testservice_testservice_proto_rawDescOnce sync.Once
	file_internal_testservice_testservice_proto_rawDescData []byte
)

func file_internal_testservice_testservice_proto_rawDescGZIP() []byte {
	file_internal_testservice_testservice_proto_rawDescOnce.Do(func() {
		file_internal_testservice_testservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testservice_testservice_proto_rawDesc), len(file_internal_testservice_testservice_proto_rawDesc)))
	})
	return file_internal_testservice_testservice_proto_rawDescData
}

var file_internal_testservice_testservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_testservice_testservice_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: elephantine.testservice.v1.EchoRequest
	(*EchoResponse)(nil), // 1: elephantine.testservice.v1.EchoResponse
	(*FailRequest)(nil),  // 2: elephantine.testservice.v1.FailRequest
	(*FailResponse)(nil), // 3: elephantine.testservice.v1.FailResponse
	nil,                  // 4: elephantine.testservice.v1.EchoResponse.LogMetadataEntry
}
var file_internal_testservice_testservice_proto_depIdxs = []int32{
	4, // 0: elephantine.testservice.v1.EchoResponse.log_metadata:type_name -> elephantine.testservice.v1.EchoResponse.LogMetadataEntry
	0, // 1: elephantine.testservice.v1.TestService.Echo:input_type -> elephantine.testservice.v1.EchoRequest
	2, // 2: elephantine.testservice.v1.TestService.Fail:input_type -> elephantine.testservice.v1.FailRequest
	1, // 3: elephantine.testservice.v1.TestService.Echo:output_type -> elephantine.testservice.v1.EchoResponse
	3, // 4: elephantine.testservice.v1.TestService.Fail:output_type -> elephantine.testservice.v1.FailResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_testservice_testservice_proto_init() }
func file_internal_testservice_testservice_proto_init() {
	if File_internal_testservice_testservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testservice_testservice_proto_rawDesc), len(file_internal_testservice_testservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_testservice_testservice_proto_goTypes,
		DependencyIndexes: file_internal_testservice_testservice_proto_depIdxs,
		MessageInfos:      file_internal_testservice_testservice_proto_msgTypes,
	}.Build()
	File_internal_testservice_testservice_proto = out.File
	file_internal_testservice_testservice_proto_goTypes = nil
	file_internal_testservice_testservice_proto_depIdxs = nil
}
