// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: testrpc/v1/service.proto

package testrpcv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ttab/elephantine/cmd/protoc-gen-elephant-rpc/testdata/withinterface/testrpc/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DocumentsName is the fully-qualified name of the Documents service.
	DocumentsName = "testrpc.v1.Documents"
	// SchemasName is the fully-qualified name of the Schemas service.
	SchemasName = "testrpc.v1.Schemas"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DocumentsGetProcedure is the fully-qualified name of the Documents's Get RPC.
	DocumentsGetProcedure = "/testrpc.v1.Documents/Get"
	// DocumentsUpdateProcedure is the fully-qualified name of the Documents's Update RPC.
	DocumentsUpdateProcedure = "/testrpc.v1.Documents/Update"
	// DocumentsDeleteProcedure is the fully-qualified name of the Documents's Delete RPC.
	DocumentsDeleteProcedure = "/testrpc.v1.Documents/Delete"
	// SchemasRegisterProcedure is the fully-qualified name of the Schemas's Register RPC.
	SchemasRegisterProcedure = "/testrpc.v1.Schemas/Register"
	// SchemasListProcedure is the fully-qualified name of the Schemas's List RPC.
	SchemasListProcedure = "/testrpc.v1.Schemas/List"
)

// DocumentsClient is a client for the testrpc.v1.Documents service.
type DocumentsClient interface {
	// Get retrieves a document version.
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
	// Update creates a new version of a document. The comment runs over more
	// than one line so that the fixture covers a multi-line doc comment being
	// carried over verbatim.
	Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
}

// NewDocumentsClient constructs a client for the testrpc.v1.Documents service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDocumentsClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DocumentsClient {
	baseURL = strings.TrimRight(baseURL, "/")
	documentsMethods := v1.File_testrpc_v1_service_proto.Services().ByName("Documents").Methods()
	return &documentsClient{
		get: connect.NewClient[v1.GetRequest, v1.GetResponse](
			httpClient,
			baseURL+DocumentsGetProcedure,
			connect.WithSchema(documentsMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.UpdateRequest, v1.UpdateResponse](
			httpClient,
			baseURL+DocumentsUpdateProcedure,
			connect.WithSchema(documentsMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.DeleteRequest, v1.DeleteResponse](
			httpClient,
			baseURL+DocumentsDeleteProcedure,
			connect.WithSchema(documentsMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// documentsClient implements DocumentsClient.
type documentsClient struct {
	get    *connect.Client[v1.GetRequest, v1.GetResponse]
	update *connect.Client[v1.UpdateRequest, v1.UpdateResponse]
	delete *connect.Client[v1.DeleteRequest, v1.DeleteResponse]
}

// Get calls testrpc.v1.Documents.Get.
func (c *documentsClient) Get(ctx context.Context, req *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Update calls testrpc.v1.Documents.Update.
func (c *documentsClient) Update(ctx context.Context, req *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls testrpc.v1.Documents.Delete.
func (c *documentsClient) Delete(ctx context.Context, req *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// DocumentsHandler is an implementation of the testrpc.v1.Documents service.
type DocumentsHandler interface {
	// Get retrieves a document version.
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
	// Update creates a new version of a document. The comment runs over more
	// than one line so that the fixture covers a multi-line doc comment being
	// carried over verbatim.
	Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
}

// NewDocumentsHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDocumentsHandler(svc DocumentsHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	documentsMethods := v1.File_testrpc_v1_service_proto.Services().ByName("Documents").Methods()
	documentsGetHandler := connect.NewUnaryHandler(
		DocumentsGetProcedure,
		svc.Get,
		connect.WithSchema(documentsMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	documentsUpdateHandler := connect.NewUnaryHandler(
		DocumentsUpdateProcedure,
		svc.Update,
		connect.WithSchema(documentsMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	documentsDeleteHandler := connect.NewUnaryHandler(
		DocumentsDeleteProcedure,
		svc.Delete,
		connect.WithSchema(documentsMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/testrpc.v1.Documents/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DocumentsGetProcedure:
			documentsGetHandler.ServeHTTP(w, r)
		case DocumentsUpdateProcedure:
			documentsUpdateHandler.ServeHTTP(w, r)
		case DocumentsDeleteProcedure:
			documentsDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDocumentsHandler returns CodeUnimplemented from all methods.
type UnimplementedDocumentsHandler struct{}

func (UnimplementedDocumentsHandler) Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("testrpc.v1.Documents.Get is not implemented"))
}

func (UnimplementedDocumentsHandler) Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("testrpc.v1.Documents.Update is not implemented"))
}

func (UnimplementedDocumentsHandler) Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("testrpc.v1.Documents.Delete is not implemented"))
}

// SchemasClient is a client for the testrpc.v1.Schemas service.
type SchemasClient interface {
	// Register adds a schema version.
	Register(context.Context, *connect.Request[v1.RegisterSchemaRequest]) (*connect.Response[v1.RegisterSchemaResponse], error)
	// List returns the registered schemas.
	List(context.Context, *connect.Request[v1.ListSchemasRequest]) (*connect.Response[v1.ListSchemasResponse], error)
}

// NewSchemasClient constructs a client for the testrpc.v1.Schemas service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSchemasClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SchemasClient {
	baseURL = strings.TrimRight(baseURL, "/")
	schemasMethods := v1.File_testrpc_v1_service_proto.Services().ByName("Schemas").Methods()
	return &schemasClient{
		register: connect.NewClient[v1.RegisterSchemaRequest, v1.RegisterSchemaResponse](
			httpClient,
			baseURL+SchemasRegisterProcedure,
			connect.WithSchema(schemasMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListSchemasRequest, v1.ListSchemasResponse](
			httpClient,
			baseURL+SchemasListProcedure,
			connect.WithSchema(schemasMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
	}
}

// schemasClient implements SchemasClient.
type schemasClient struct {
	register *connect.Client[v1.RegisterSchemaRequest, v1.RegisterSchemaResponse]
	list     *connect.Client[v1.ListSchemasRequest, v1.ListSchemasResponse]
}

// Register calls testrpc.v1.Schemas.Register.
func (c *schemasClient) Register(ctx context.Context, req *connect.Request[v1.RegisterSchemaRequest]) (*connect.Response[v1.RegisterSchemaResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// List calls testrpc.v1.Schemas.List.
func (c *schemasClient) List(ctx context.Context, req *connect.Request[v1.ListSchemasRequest]) (*connect.Response[v1.ListSchemasResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// SchemasHandler is an implementation of the testrpc.v1.Schemas service.
type SchemasHandler interface {
	// Register adds a schema version.
	Register(context.Context, *connect.Request[v1.RegisterSchemaRequest]) (*connect.Response[v1.RegisterSchemaResponse], error)
	// List returns the registered schemas.
	List(context.Context, *connect.Request[v1.ListSchemasRequest]) (*connect.Response[v1.ListSchemasResponse], error)
}

// NewSchemasHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSchemasHandler(svc SchemasHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	schemasMethods := v1.File_testrpc_v1_service_proto.Services().ByName("Schemas").Methods()
	schemasRegisterHandler := connect.NewUnaryHandler(
		SchemasRegisterProcedure,
		svc.Register,
		connect.WithSchema(schemasMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	schemasListHandler := connect.NewUnaryHandler(
		SchemasListProcedure,
		svc.List,
		connect.WithSchema(schemasMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	return "/testrpc.v1.Schemas/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SchemasRegisterProcedure:
			schemasRegisterHandler.ServeHTTP(w, r)
		case SchemasListProcedure:
			schemasListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSchemasHandler returns CodeUnimplemented from all methods.
type UnimplementedSchemasHandler struct{}

func (UnimplementedSchemasHandler) Register(context.Context, *connect.Request[v1.RegisterSchemaRequest]) (*connect.Response[v1.RegisterSchemaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("testrpc.v1.Schemas.Register is not implemented"))
}

func (UnimplementedSchemasHandler) List(context.Context, *connect.Request[v1.ListSchemasRequest]) (*connect.Response[v1.ListSchemasResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("testrpc.v1.Schemas.List is not implemented"))
}
