// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: testrpc/v1/service.proto

package testrpcv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "github.com/ttab/elephantine/cmd/protoc-gen-elephant-rpc/testdata/withinterface/testrpc/v1"
	http "net/http"
)

// NewDocumentsServiceHandler builds an HTTP handler for the testrpc.v1.Documents service from an
// implementation of the plain v1.Documents interface, and returns the path to mount it on together
// with the handler, just like NewDocumentsHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewDocumentsServiceHandler(svc v1.Documents, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewDocumentsHandler(&documentsServiceHandler{svc: svc}, opts...)
}

// documentsServiceHandler implements DocumentsHandler on top of a v1.Documents.
type documentsServiceHandler struct {
	svc v1.Documents
}

func (h *documentsServiceHandler) Get(ctx context.Context, req *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	res, err := h.svc.Get(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Update(ctx context.Context, req *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error) {
	res, err := h.svc.Update(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Delete(ctx context.Context, req *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	res, err := h.svc.Delete(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewDocumentsServiceClient constructs a client for the testrpc.v1.Documents service that
// implements the plain v1.Documents interface, so that it is a drop-in for the Twirp clients. The
// options are the ones NewDocumentsClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewDocumentsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) v1.Documents {
	return &documentsServiceClient{
		client: NewDocumentsClient(httpClient, baseURL, opts...),
	}
}

// documentsServiceClient implements v1.Documents on top of a DocumentsClient.
type documentsServiceClient struct {
	client DocumentsClient
}

func (c *documentsServiceClient) Get(ctx context.Context, req *v1.GetRequest) (*v1.GetResponse, error) {
	res, err := c.client.Get(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Update(ctx context.Context, req *v1.UpdateRequest) (*v1.UpdateResponse, error) {
	res, err := c.client.Update(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Delete(ctx context.Context, req *v1.DeleteRequest) (*v1.DeleteResponse, error) {
	res, err := c.client.Delete(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewSchemasServiceHandler builds an HTTP handler for the testrpc.v1.Schemas service from an
// implementation of the plain v1.Schemas interface, and returns the path to mount it on together
// with the handler, just like NewSchemasHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewSchemasServiceHandler(svc v1.Schemas, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewSchemasHandler(&schemasServiceHandler{svc: svc}, opts...)
}

// schemasServiceHandler implements SchemasHandler on top of a v1.Schemas.
type schemasServiceHandler struct {
	svc v1.Schemas
}

func (h *schemasServiceHandler) Register(ctx context.Context, req *connect.Request[v1.RegisterSchemaRequest]) (*connect.Response[v1.RegisterSchemaResponse], error) {
	res, err := h.svc.Register(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) List(ctx context.Context, req *connect.Request[v1.ListSchemasRequest]) (*connect.Response[v1.ListSchemasResponse], error) {
	res, err := h.svc.List(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewSchemasServiceClient constructs a client for the testrpc.v1.Schemas service that implements
// the plain v1.Schemas interface, so that it is a drop-in for the Twirp clients. The options are
// the ones NewSchemasClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewSchemasServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) v1.Schemas {
	return &schemasServiceClient{
		client: NewSchemasClient(httpClient, baseURL, opts...),
	}
}

// schemasServiceClient implements v1.Schemas on top of a SchemasClient.
type schemasServiceClient struct {
	client SchemasClient
}

func (c *schemasServiceClient) Register(ctx context.Context, req *v1.RegisterSchemaRequest) (*v1.RegisterSchemaResponse, error) {
	res, err := c.client.Register(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) List(ctx context.Context, req *v1.ListSchemasRequest) (*v1.ListSchemasResponse, error) {
	res, err := c.client.List(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
