// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: testrpc/v1/service.proto

package testrpcv1

import (
	context "context"
)

// Documents is the service that stores and retrieves documents. The comment
// is here to check that a service level doc comment ends up on the generated
// interface, the way protoc-gen-twirp puts it there.
type Documents interface {
	// Get retrieves a document version.
	Get(context.Context, *GetRequest) (*GetResponse, error)

	// Update creates a new version of a document. The comment runs over more
	// than one line so that the fixture covers a multi-line doc comment being
	// carried over verbatim.
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)

	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// Schemas manages the document schemas.
type Schemas interface {
	// Register adds a schema version.
	Register(context.Context, *RegisterSchemaRequest) (*RegisterSchemaResponse, error)

	// List returns the registered schemas.
	List(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
}
