// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: testrpc/v1/service.proto

package testrpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_testrpc_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_testrpc_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_testrpc_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_testrpc_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_testrpc_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_testrpc_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{5}
}

type RegisterSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSchemaRequest) Reset() {
	*x = RegisterSchemaRequest{}
	mi := &file_testrpc_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaRequest) ProtoMessage() {}

func (x *RegisterSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaRequest.ProtoReflect.Descriptor instead.
func (*RegisterSchemaRequest) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterSchemaRequest) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type RegisterSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSchemaResponse) Reset() {
	*x = RegisterSchemaResponse{}
	mi := &file_testrpc_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaResponse) ProtoMessage() {}

func (x *RegisterSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaResponse.ProtoReflect.Descriptor instead.
func (*RegisterSchemaResponse) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{7}
}

type ListSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasRequest) Reset() {
	*x = ListSchemasRequest{}
	mi := &file_testrpc_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasRequest) ProtoMessage() {}

func (x *ListSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListSchemasRequest) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{8}
}

type ListSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*Schema              `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_testrpc_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListSchemasResponse) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

var File_testrpc_v1_service_proto protoreflect.FileDescriptor

const file_testrpc_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18testrpc/v1/service.proto\x12\n" +
	"testrpc.v1\x1a\x16testrpc/v1/types.proto\":\n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"?\n" +
	"\vGetResponse\x120\n" +
	"\bdocument\x18\x01 \x01(\v2\x14.testrpc.v1.DocumentR\bdocument\"A\n" +
	"\rUpdateRequest\x120\n" +
	"\bdocument\x18\x01 \x01(\v2\x14.testrpc.v1.DocumentR\bdocument\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x10\n" +
	"\x0eDeleteResponse\"C\n" +
	"\x15RegisterSchemaRequest\x12*\n" +
	"\x06schema\x18\x01 \x01(\v2\x12.testrpc.v1.SchemaR\x06schema\"\x18\n" +
	"\x16RegisterSchemaResponse\"\x14\n" +
	"\x12ListSchemasRequest\"C\n" +
	"\x13ListSchemasResponse\x12,\n" +
	"\aschemas\x18\x01 \x03(\v2\x12.testrpc.v1.SchemaR\aschemas2\xc5\x01\n" +
	"\tDocuments\x126\n" +
	"\x03Get\x12\x16.testrpc.v1.GetRequest\x1a\x17.testrpc.v1.GetResponse\x12?\n" +
	"\x06Update\x12\x19.testrpc.v1.UpdateRequest\x1a\x1a.testrpc.v1.UpdateResponse\x12?\n" +
	"\x06Delete\x12\x19.testrpc.v1.DeleteRequest\x1a\x1a.testrpc.v1.DeleteResponse2\xa5\x01\n" +
	"\aSchemas\x12Q\n" +
	"\bRegister\x12!.testrpc.v1.RegisterSchemaRequest\x1a\".testrpc.v1.RegisterSchemaResponse\x12G\n" +
	"\x04List\x12\x1e.testrpc.v1.ListSchemasRequest\x1a\x1f.testrpc.v1.ListSchemasResponseBWZUgithub.com/ttab/elephantine/cmd/protoc-gen-elephant-rpc/testdata/testrpc/v1;testrpcv1b\x06proto3"

var (
	file_testrpc_v1_service_proto_rawDescOnce sync.Once
	file_testrpc_v1_service_proto_rawDescData []byte
)

func file_testrpc_v1_service_proto_rawDescGZIP() []byte {
	file_testrpc_v1_service_proto_rawDescOnce.Do(func() {
		file_testrpc_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testrpc_v1_service_proto_rawDesc), len(file_testrpc_v1_service_proto_rawDesc)))
	})
	return file_testrpc_v1_service_proto_rawDescData
}

var file_testrpc_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_testrpc_v1_service_proto_goTypes = []any{
	(*GetRequest)(nil),             // 0: testrpc.v1.GetRequest
	(*GetResponse)(nil),            // 1: testrpc.v1.GetResponse
	(*UpdateRequest)(nil),          // 2: testrpc.v1.UpdateRequest
	(*UpdateResponse)(nil),         // 3: testrpc.v1.UpdateResponse
	(*DeleteRequest)(nil),          // 4: testrpc.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 5: testrpc.v1.DeleteResponse
	(*RegisterSchemaRequest)(nil),  // 6: testrpc.v1.RegisterSchemaRequest
	(*RegisterSchemaResponse)(nil), // 7: testrpc.v1.RegisterSchemaResponse
	(*ListSchemasRequest)(nil),     // 8: testrpc.v1.ListSchemasRequest
	(*ListSchemasResponse)(nil),    // 9: testrpc.v1.ListSchemasResponse
	(*Document)(nil),               // 10: testrpc.v1.Document
	(*Schema)(nil),                 // 11: testrpc.v1.Schema
}
var file_testrpc_v1_service_proto_depIdxs = []int32{
	10, // 0: testrpc.v1.GetResponse.document:type_name -> testrpc.v1.Document
	10, // 1: testrpc.v1.UpdateRequest.document:type_name -> testrpc.v1.Document
	11, // 2: testrpc.v1.RegisterSchemaRequest.schema:type_name -> testrpc.v1.Schema
	11, // 3: testrpc.v1.ListSchemasResponse.schemas:type_name -> testrpc.v1.Schema
	0,  // 4: testrpc.v1.Documents.Get:input_type -> testrpc.v1.GetRequest
	2,  // 5: testrpc.v1.Documents.Update:input_type -> testrpc.v1.UpdateRequest
	4,  // 6: testrpc.v1.Documents.Delete:input_type -> testrpc.v1.DeleteRequest
	6,  // 7: testrpc.v1.Schemas.Register:input_type -> testrpc.v1.RegisterSchemaRequest
	8,  // 8: testrpc.v1.Schemas.List:input_type -> testrpc.v1.ListSchemasRequest
	1,  // 9: testrpc.v1.Documents.Get:output_type -> testrpc.v1.GetResponse
	3,  // 10: testrpc.v1.Documents.Update:output_type -> testrpc.v1.UpdateResponse
	5,  // 11: testrpc.v1.Documents.Delete:output_type -> testrpc.v1.DeleteResponse
	7,  // 12: testrpc.v1.Schemas.Register:output_type -> testrpc.v1.RegisterSchemaResponse
	9,  // 13: testrpc.v1.Schemas.List:output_type -> testrpc.v1.ListSchemasResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_testrpc_v1_service_proto_init() }
func file_testrpc_v1_service_proto_init() {
	if File_testrpc_v1_service_proto != nil {
		return
	}
	file_testrpc_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testrpc_v1_service_proto_rawDesc), len(file_testrpc_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_testrpc_v1_service_proto_goTypes,
		DependencyIndexes: file_testrpc_v1_service_proto_depIdxs,
		MessageInfos:      file_testrpc_v1_service_proto_msgTypes,
	}.Build()
	File_testrpc_v1_service_proto = out.File
	file_testrpc_v1_service_proto_goTypes = nil
	file_testrpc_v1_service_proto_depIdxs = nil
}
