// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: testrpc/v1/types.proto

package testrpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document is the message the fixture services pass around. This file has no
// services, so the plugin must not generate anything for it.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid identifies the document.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// title is the human readable name of the document.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// version is the version number of the document.
	Version       int64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_testrpc_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Schema describes the shape a document type has to have.
type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Specification []byte                 `protobuf:"bytes,3,opt,name=specification,proto3" json:"specification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_testrpc_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_testrpc_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_testrpc_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Schema) GetSpecification() []byte {
	if x != nil {
		return x.Specification
	}
	return nil
}

var File_testrpc_v1_types_proto protoreflect.FileDescriptor

const file_testrpc_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x16testrpc/v1/types.proto\x12\n" +
	"testrpc.v1\"N\n" +
	"\bDocument\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\\\n" +
	"\x06Schema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12$\n" +
	"\rspecification\x18\x03 \x01(\fR\rspecificationBWZUgithub.com/ttab/elephantine/cmd/protoc-gen-elephant-rpc/testdata/testrpc/v1;testrpcv1b\x06proto3"

var (
	file_testrpc_v1_types_proto_rawDescOnce sync.Once
	file_testrpc_v1_types_proto_rawDescData []byte
)

func file_testrpc_v1_types_proto_rawDescGZIP() []byte {
	file_testrpc_v1_types_proto_rawDescOnce.Do(func() {
		file_testrpc_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testrpc_v1_types_proto_rawDesc), len(file_testrpc_v1_types_proto_rawDesc)))
	})
	return file_testrpc_v1_types_proto_rawDescData
}

var file_testrpc_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testrpc_v1_types_proto_goTypes = []any{
	(*Document)(nil), // 0: testrpc.v1.Document
	(*Schema)(nil),   // 1: testrpc.v1.Schema
}
var file_testrpc_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testrpc_v1_types_proto_init() }
func file_testrpc_v1_types_proto_init() {
	if File_testrpc_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testrpc_v1_types_proto_rawDesc), len(file_testrpc_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testrpc_v1_types_proto_goTypes,
		DependencyIndexes: file_testrpc_v1_types_proto_depIdxs,
		MessageInfos:      file_testrpc_v1_types_proto_msgTypes,
	}.Build()
	File_testrpc_v1_types_proto = out.File
	file_testrpc_v1_types_proto_goTypes = nil
	file_testrpc_v1_types_proto_depIdxs = nil
}
