// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/testservice/stream.proto

package testserviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	testservice "github.com/ttab/elephantine/internal/testservice"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StreamServiceName is the fully-qualified name of the StreamService service.
	StreamServiceName = "elephantine.testservice.v1.StreamService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StreamServiceEmitProcedure is the fully-qualified name of the StreamService's Emit RPC.
	StreamServiceEmitProcedure = "/elephantine.testservice.v1.StreamService/Emit"
	// StreamServiceCollectProcedure is the fully-qualified name of the StreamService's Collect RPC.
	StreamServiceCollectProcedure = "/elephantine.testservice.v1.StreamService/Collect"
	// StreamServiceExchangeProcedure is the fully-qualified name of the StreamService's Exchange RPC.
	StreamServiceExchangeProcedure = "/elephantine.testservice.v1.StreamService/Exchange"
)

// StreamServiceClient is a client for the elephantine.testservice.v1.StreamService service.
type StreamServiceClient interface {
	// Emit sends the requested number of messages, and can be told to fail
	// after the first, to stay open until its context is done, or to end when
	// the caller's token expires.
	Emit(context.Context, *connect.Request[testservice.EmitRequest]) (*connect.ServerStreamForClient[testservice.EmitResponse], error)
	// Collect counts the messages and the bytes it is sent.
	Collect(context.Context) *connect.ClientStreamForClient[testservice.CollectRequest, testservice.CollectResponse]
	// Exchange echoes every message it is sent.
	Exchange(context.Context) *connect.BidiStreamForClient[testservice.ExchangeRequest, testservice.ExchangeResponse]
}

// NewStreamServiceClient constructs a client for the elephantine.testservice.v1.StreamService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStreamServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StreamServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	streamServiceMethods := testservice.File_internal_testservice_stream_proto.Services().ByName("StreamService").Methods()
	return &streamServiceClient{
		emit: connect.NewClient[testservice.EmitRequest, testservice.EmitResponse](
			httpClient,
			baseURL+StreamServiceEmitProcedure,
			connect.WithSchema(streamServiceMethods.ByName("Emit")),
			connect.WithClientOptions(opts...),
		),
		collect: connect.NewClient[testservice.CollectRequest, testservice.CollectResponse](
			httpClient,
			baseURL+StreamServiceCollectProcedure,
			connect.WithSchema(streamServiceMethods.ByName("Collect")),
			connect.WithClientOptions(opts...),
		),
		exchange: connect.NewClient[testservice.ExchangeRequest, testservice.ExchangeResponse](
			httpClient,
			baseURL+StreamServiceExchangeProcedure,
			connect.WithSchema(streamServiceMethods.ByName("Exchange")),
			connect.WithClientOptions(opts...),
		),
	}
}

// streamServiceClient implements StreamServiceClient.
type streamServiceClient struct {
	emit     *connect.Client[testservice.EmitRequest, testservice.EmitResponse]
	collect  *connect.Client[testservice.CollectRequest, testservice.CollectResponse]
	exchange *connect.Client[testservice.ExchangeRequest, testservice.ExchangeResponse]
}

// Emit calls elephantine.testservice.v1.StreamService.Emit.
func (c *streamServiceClient) Emit(ctx context.Context, req *connect.Request[testservice.EmitRequest]) (*connect.ServerStreamForClient[testservice.EmitResponse], error) {
	return c.emit.CallServerStream(ctx, req)
}

// Collect calls elephantine.testservice.v1.StreamService.Collect.
func (c *streamServiceClient) Collect(ctx context.Context) *connect.ClientStreamForClient[testservice.CollectRequest, testservice.CollectResponse] {
	return c.collect.CallClientStream(ctx)
}

// Exchange calls elephantine.testservice.v1.StreamService.Exchange.
func (c *streamServiceClient) Exchange(ctx context.Context) *connect.BidiStreamForClient[testservice.ExchangeRequest, testservice.ExchangeResponse] {
	return c.exchange.CallBidiStream(ctx)
}

// StreamServiceHandler is an implementation of the elephantine.testservice.v1.StreamService
// service.
type StreamServiceHandler interface {
	// Emit sends the requested number of messages, and can be told to fail
	// after the first, to stay open until its context is done, or to end when
	// the caller's token expires.
	Emit(context.Context, *connect.Request[testservice.EmitRequest], *connect.ServerStream[testservice.EmitResponse]) error
	// Collect counts the messages and the bytes it is sent.
	Collect(context.Context, *connect.ClientStream[testservice.CollectRequest]) (*connect.Response[testservice.CollectResponse], error)
	// Exchange echoes every message it is sent.
	Exchange(context.Context, *connect.BidiStream[testservice.ExchangeRequest, testservice.ExchangeResponse]) error
}

// NewStreamServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStreamServiceHandler(svc StreamServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	streamServiceMethods := testservice.File_internal_testservice_stream_proto.Services().ByName("StreamService").Methods()
	streamServiceEmitHandler := connect.NewServerStreamHandler(
		StreamServiceEmitProcedure,
		svc.Emit,
		connect.WithSchema(streamServiceMethods.ByName("Emit")),
		connect.WithHandlerOptions(opts...),
	)
	streamServiceCollectHandler := connect.NewClientStreamHandler(
		StreamServiceCollectProcedure,
		svc.Collect,
		connect.WithSchema(streamServiceMethods.ByName("Collect")),
		connect.WithHandlerOptions(opts...),
	)
	streamServiceExchangeHandler := connect.NewBidiStreamHandler(
		StreamServiceExchangeProcedure,
		svc.Exchange,
		connect.WithSchema(streamServiceMethods.ByName("Exchange")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elephantine.testservice.v1.StreamService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StreamServiceEmitProcedure:
			streamServiceEmitHandler.ServeHTTP(w, r)
		case StreamServiceCollectProcedure:
			streamServiceCollectHandler.ServeHTTP(w, r)
		case StreamServiceExchangeProcedure:
			streamServiceExchangeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStreamServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStreamServiceHandler struct{}

func (UnimplementedStreamServiceHandler) Emit(context.Context, *connect.Request[testservice.EmitRequest], *connect.ServerStream[testservice.EmitResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("elephantine.testservice.v1.StreamService.Emit is not implemented"))
}

func (UnimplementedStreamServiceHandler) Collect(context.Context, *connect.ClientStream[testservice.CollectRequest]) (*connect.Response[testservice.CollectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephantine.testservice.v1.StreamService.Collect is not implemented"))
}

func (UnimplementedStreamServiceHandler) Exchange(context.Context, *connect.BidiStream[testservice.ExchangeRequest, testservice.ExchangeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("elephantine.testservice.v1.StreamService.Exchange is not implemented"))
}
