// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: internal/testservice/testservice.proto

package testserviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	testservice "github.com/ttab/elephantine/internal/testservice"
	http "net/http"
)

// NewTestServiceServiceHandler builds an HTTP handler for the
// elephantine.testservice.v1.TestService service from an implementation of the plain
// testservice.TestService interface, and returns the path to mount it on together with the handler,
// just like NewTestServiceHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewTestServiceServiceHandler(svc testservice.TestService, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewTestServiceHandler(&testServiceServiceHandler{svc: svc}, opts...)
}

// testServiceServiceHandler implements TestServiceHandler on top of a testservice.TestService.
type testServiceServiceHandler struct {
	svc testservice.TestService
}

func (h *testServiceServiceHandler) Echo(ctx context.Context, req *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error) {
	res, err := h.svc.Echo(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *testServiceServiceHandler) Fail(ctx context.Context, req *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error) {
	res, err := h.svc.Fail(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewTestServiceServiceClient constructs a client for the elephantine.testservice.v1.TestService
// service that implements the plain testservice.TestService interface, so that it is a drop-in for
// the Twirp clients. The options are the ones NewTestServiceClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewTestServiceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) testservice.TestService {
	return &testServiceServiceClient{
		client: NewTestServiceClient(httpClient, baseURL, opts...),
	}
}

// testServiceServiceClient implements testservice.TestService on top of a TestServiceClient.
type testServiceServiceClient struct {
	client TestServiceClient
}

func (c *testServiceServiceClient) Echo(ctx context.Context, req *testservice.EchoRequest) (*testservice.EchoResponse, error) {
	res, err := c.client.Echo(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *testServiceServiceClient) Fail(ctx context.Context, req *testservice.FailRequest) (*testservice.FailResponse, error) {
	res, err := c.client.Fail(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
