// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/testservice/testservice.proto

package testserviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	testservice "github.com/ttab/elephantine/internal/testservice"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TestServiceName is the fully-qualified name of the TestService service.
	TestServiceName = "elephantine.testservice.v1.TestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TestServiceEchoProcedure is the fully-qualified name of the TestService's Echo RPC.
	TestServiceEchoProcedure = "/elephantine.testservice.v1.TestService/Echo"
	// TestServiceFailProcedure is the fully-qualified name of the TestService's Fail RPC.
	TestServiceFailProcedure = "/elephantine.testservice.v1.TestService/Fail"
)

// TestServiceClient is a client for the elephantine.testservice.v1.TestService service.
type TestServiceClient interface {
	// Echo returns the message it was given, together with what the service
	// could see of the caller.
	Echo(context.Context, *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error)
	// Fail returns an error with the requested code and error metadata.
	Fail(context.Context, *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error)
}

// NewTestServiceClient constructs a client for the elephantine.testservice.v1.TestService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	testServiceMethods := testservice.File_internal_testservice_testservice_proto.Services().ByName("TestService").Methods()
	return &testServiceClient{
		echo: connect.NewClient[testservice.EchoRequest, testservice.EchoResponse](
			httpClient,
			baseURL+TestServiceEchoProcedure,
			connect.WithSchema(testServiceMethods.ByName("Echo")),
			connect.WithClientOptions(opts...),
		),
		fail: connect.NewClient[testservice.FailRequest, testservice.FailResponse](
			httpClient,
			baseURL+TestServiceFailProcedure,
			connect.WithSchema(testServiceMethods.ByName("Fail")),
			connect.WithClientOptions(opts...),
		),
	}
}

// testServiceClient implements TestServiceClient.
type testServiceClient struct {
	echo *connect.Client[testservice.EchoRequest, testservice.EchoResponse]
	fail *connect.Client[testservice.FailRequest, testservice.FailResponse]
}

// Echo calls elephantine.testservice.v1.TestService.Echo.
func (c *testServiceClient) Echo(ctx context.Context, req *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error) {
	return c.echo.CallUnary(ctx, req)
}

// Fail calls elephantine.testservice.v1.TestService.Fail.
func (c *testServiceClient) Fail(ctx context.Context, req *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error) {
	return c.fail.CallUnary(ctx, req)
}

// TestServiceHandler is an implementation of the elephantine.testservice.v1.TestService service.
type TestServiceHandler interface {
	// Echo returns the message it was given, together with what the service
	// could see of the caller.
	Echo(context.Context, *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error)
	// Fail returns an error with the requested code and error metadata.
	Fail(context.Context, *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error)
}

// NewTestServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTestServiceHandler(svc TestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	testServiceMethods := testservice.File_internal_testservice_testservice_proto.Services().ByName("TestService").Methods()
	testServiceEchoHandler := connect.NewUnaryHandler(
		TestServiceEchoProcedure,
		svc.Echo,
		connect.WithSchema(testServiceMethods.ByName("Echo")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceFailHandler := connect.NewUnaryHandler(
		TestServiceFailProcedure,
		svc.Fail,
		connect.WithSchema(testServiceMethods.ByName("Fail")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elephantine.testservice.v1.TestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TestServiceEchoProcedure:
			testServiceEchoHandler.ServeHTTP(w, r)
		case TestServiceFailProcedure:
			testServiceFailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTestServiceHandler struct{}

func (UnimplementedTestServiceHandler) Echo(context.Context, *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephantine.testservice.v1.TestService.Echo is not implemented"))
}

func (UnimplementedTestServiceHandler) Fail(context.Context, *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephantine.testservice.v1.TestService.Fail is not implemented"))
}
