// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/testservice/testservice.proto

package testserviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	testservice "github.com/ttab/elephantine/internal/testservice"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TestName is the fully-qualified name of the Test service.
	TestName = "elephantine.testservice.v1.Test"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TestEchoProcedure is the fully-qualified name of the Test's Echo RPC.
	TestEchoProcedure = "/elephantine.testservice.v1.Test/Echo"
	// TestFailProcedure is the fully-qualified name of the Test's Fail RPC.
	TestFailProcedure = "/elephantine.testservice.v1.Test/Fail"
)

// TestClient is a client for the elephantine.testservice.v1.Test service.
type TestClient interface {
	// Echo returns the message it was given, together with what the service
	// could see of the caller.
	Echo(context.Context, *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error)
	// Fail returns an error with the requested code and error metadata.
	Fail(context.Context, *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error)
}

// NewTestClient constructs a client for the elephantine.testservice.v1.Test service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTestClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TestClient {
	baseURL = strings.TrimRight(baseURL, "/")
	testMethods := testservice.File_internal_testservice_testservice_proto.Services().ByName("Test").Methods()
	return &testClient{
		echo: connect.NewClient[testservice.EchoRequest, testservice.EchoResponse](
			httpClient,
			baseURL+TestEchoProcedure,
			connect.WithSchema(testMethods.ByName("Echo")),
			connect.WithClientOptions(opts...),
		),
		fail: connect.NewClient[testservice.FailRequest, testservice.FailResponse](
			httpClient,
			baseURL+TestFailProcedure,
			connect.WithSchema(testMethods.ByName("Fail")),
			connect.WithClientOptions(opts...),
		),
	}
}

// testClient implements TestClient.
type testClient struct {
	echo *connect.Client[testservice.EchoRequest, testservice.EchoResponse]
	fail *connect.Client[testservice.FailRequest, testservice.FailResponse]
}

// Echo calls elephantine.testservice.v1.Test.Echo.
func (c *testClient) Echo(ctx context.Context, req *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error) {
	return c.echo.CallUnary(ctx, req)
}

// Fail calls elephantine.testservice.v1.Test.Fail.
func (c *testClient) Fail(ctx context.Context, req *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error) {
	return c.fail.CallUnary(ctx, req)
}

// TestHandler is an implementation of the elephantine.testservice.v1.Test service.
type TestHandler interface {
	// Echo returns the message it was given, together with what the service
	// could see of the caller.
	Echo(context.Context, *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error)
	// Fail returns an error with the requested code and error metadata.
	Fail(context.Context, *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error)
}

// NewTestHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTestHandler(svc TestHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	testMethods := testservice.File_internal_testservice_testservice_proto.Services().ByName("Test").Methods()
	testEchoHandler := connect.NewUnaryHandler(
		TestEchoProcedure,
		svc.Echo,
		connect.WithSchema(testMethods.ByName("Echo")),
		connect.WithHandlerOptions(opts...),
	)
	testFailHandler := connect.NewUnaryHandler(
		TestFailProcedure,
		svc.Fail,
		connect.WithSchema(testMethods.ByName("Fail")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elephantine.testservice.v1.Test/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TestEchoProcedure:
			testEchoHandler.ServeHTTP(w, r)
		case TestFailProcedure:
			testFailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTestHandler returns CodeUnimplemented from all methods.
type UnimplementedTestHandler struct{}

func (UnimplementedTestHandler) Echo(context.Context, *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephantine.testservice.v1.Test.Echo is not implemented"))
}

func (UnimplementedTestHandler) Fail(context.Context, *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephantine.testservice.v1.Test.Fail is not implemented"))
}
