// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: internal/testservice/testservice.proto

package testserviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	testservice "github.com/ttab/elephantine/internal/testservice"
	http "net/http"
)

// NewTestServiceHandler builds an HTTP handler for the elephantine.testservice.v1.Test service from
// an implementation of the plain testservice.Test interface, and returns the path to mount it on
// together with the handler, just like NewTestHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewTestServiceHandler(svc testservice.Test, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewTestHandler(&testServiceHandler{svc: svc}, opts...)
}

// testServiceHandler implements TestHandler on top of a testservice.Test.
type testServiceHandler struct {
	svc testservice.Test
}

func (h *testServiceHandler) Echo(ctx context.Context, req *connect.Request[testservice.EchoRequest]) (*connect.Response[testservice.EchoResponse], error) {
	res, err := h.svc.Echo(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *testServiceHandler) Fail(ctx context.Context, req *connect.Request[testservice.FailRequest]) (*connect.Response[testservice.FailResponse], error) {
	res, err := h.svc.Fail(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewTestServiceClient constructs a client for the elephantine.testservice.v1.Test service that
// implements the plain testservice.Test interface, so that it is a drop-in for the Twirp clients.
// The options are the ones NewTestClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewTestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) testservice.Test {
	return &testServiceClient{
		client: NewTestClient(httpClient, baseURL, opts...),
	}
}

// testServiceClient implements testservice.Test on top of a TestClient.
type testServiceClient struct {
	client TestClient
}

func (c *testServiceClient) Echo(ctx context.Context, req *testservice.EchoRequest) (*testservice.EchoResponse, error) {
	res, err := c.client.Echo(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *testServiceClient) Fail(ctx context.Context, req *testservice.FailRequest) (*testservice.FailResponse, error) {
	res, err := c.client.Fail(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
